# YOLOv11 Segmentation Training Configuration
# 곤포사일리지 데이터셋 학습 설정

# Dataset
data: E:/namwon_ai/dataset_silage_bale_rgb/dataset.yaml

# Model
model: yolo11n-seg.pt  # n, s, m, l, x

# Training
epochs: 100
batch: 16
imgsz: 640
device: 0  # GPU 0 사용 (CPU는 'cpu')
workers: 8

# Project
project: runs/segment
name: silage_bale_baseline

# Optimizer
optimizer: AdamW
lr0: 0.01      # Initial learning rate
lrf: 0.01      # Final learning rate (lr0 * lrf)
momentum: 0.937
weight_decay: 0.0005

# Training settings
patience: 50   # Early stopping patience
save: true
save_period: 10  # Save checkpoint every N epochs
cos_lr: false   # Cosine LR scheduler
close_mosaic: 10  # Disable mosaic augmentation for final epochs

# Data Augmentation
hsv_h: 0.015      # Image HSV-Hue augmentation (fraction)
hsv_s: 0.7        # Image HSV-Saturation augmentation (fraction)
hsv_v: 0.4        # Image HSV-Value augmentation (fraction)
degrees: 0.0      # Image rotation (+/- deg)
translate: 0.1    # Image translation (+/- fraction)
scale: 0.5        # Image scale (+/- gain)
shear: 0.0        # Image shear (+/- deg)
perspective: 0.0  # Image perspective (+/- fraction)
flipud: 0.0       # Image flip up-down (probability)
fliplr: 0.5       # Image flip left-right (probability)
mosaic: 1.0       # Image mosaic (probability)
mixup: 0.0        # Image mixup (probability)
copy_paste: 0.0   # Segment copy-paste (probability)

# Validation
val: true
plots: true
verbose: true

# Notes
# - 이 설정은 baseline 실험용입니다
# - 더 나은 성능을 위해 하이퍼파라미터 튜닝이 필요할 수 있습니다
# - Augmentation 파라미터는 데이터셋 특성에 맞게 조정하세요
